name: egypt_music_community
description: A new Flutter project for finding musicians and studios in Egypt.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.6

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # UI & Maps

  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utils
  geolocator: ^10.1.0
  uuid: ^4.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.7
  
  # Routing
  go_router: ^13.0.0
  timeago: ^3.7.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
